# mpc
receding: 50
step_time: 0.05
ref_speed: 0.2
device: 'cpu'
time_print: False
collision_threshold: 0.0

# robot
robot:
  kinematics: 'diff'
  max_speed: [0.2, 0.3]
  max_acce: [0.2, 0.15]
  length: 0.20
  width: 0.11

# initial path
ipath:
  interval: 0.1
  # waypoints: [[0, 0, 0], [1, 0, 0]]
  curve_style: 'line'   # 'dubins' or reeds or line
  min_radius: 0.0
  loop: False
  arrive_threshold: 0.3
  close_threshold: 0.05
  arrive_index_threshold: 3
  
# proximal alternating minimization network
pan:
  iter_num: 5
  dune_max_num: 1000
  nrmp_max_num: 10
  dune_checkpoint: None
  iter_threshold: 0.1

# adjust parameters
adjust:
  q_s: 0.1
  p_u: 100.0
  eta: 0.0
  d_max: 0.2
  d_min: -0.05
